LeadHistoryStatus.create name: "電話対応", type: "ing", color: "C8E4FF"
LeadHistoryStatus.create name: "メール対応", type: "ing", color: "C8E4FF"
LeadHistoryStatus.create name: "不在・離席", type: "ing", color: "FAF18D"
LeadHistoryStatus.create name: "時期改め", type: "ing", color: "FAF18D"
LeadHistoryStatus.create name: "再アプローチ", type: "ing", color: "577A05"
LeadHistoryStatus.create name: "保留・検討", type: "ing", color: "577A05"
LeadHistoryStatus.create name: "アポイント", type: "done", color: "F7863C"
LeadHistoryStatus.create name: "資料請求", type: "done", color: "F7863C"
LeadHistoryStatus.create name: "担当NG", type: "done", color: "7e5f00"
LeadHistoryStatus.create name: "受付NG", type: "done", color: "7e5f00"
LeadHistoryStatus.create name: "ガチャ切り", type: "done", color: "CD4232"
LeadHistoryStatus.create name: "クレーム", type: "done", color: "CD4232"
LeadHistoryStatus.create name: "不通・移転", type: "forbidden", color: "444444"
LeadHistoryStatus.create name: "荷電禁止", type: "forbidden", color: "444444"

