
TaskType.create(:name => '新規FAXフォロー', :default_due => 3, :tag => "フォロー")
TaskType.create(:name => '資料請求後フォロー', :default_due => 5, :tag => "フォロー")
TaskType.create(:name => 'カリキュラム作成',:default_assignee => 7 , :default_due => 1, :tag => "作成系")
TaskType.create(:name => '提案書作成',:default_assignee => 7, :default_due => 1, :tag => "作成系")
TaskType.create(:name => '見積作成',:default_assignee => 7, :default_due => 1, :tag => "作成系")
TaskType.create(:name => '荷電', :tag => "汎用系")
TaskType.create(:name => 'アポイント',  :tag => "汎用系")
TaskType.create(:name => 'その他',  :tag => "汎用系")
TaskType.create(:default_due => 5, :name => '提案後フォロー',  :tag => "フォロー")
